server:
  port: 0
# Conexion a la BD
spring:
  datasource:
    url: jdbc:postgresql://localhost:5440/db_parametros
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
    hikari:
      register-mbeans: true
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  boot:
    admin:
      client:
        url: http://localhost:8089
# Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      show-components: always
  tracing:
    sampling:
      probability: 1.0
# Eureka
eureka:
  instance:
    instance-id: ${spring.application.name}-${random.uuid}
    health-check-url-path: /actuator/health
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
